name: "run-tests"
description: "run-tests"

runs:
  using: "composite"
  steps:

    - name: Install Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Use the desired Python version

    - name: Install dependencies
      shell: bash
      run: |
        # python -m pip install --upgrade pip        
        pip install -r requirements-test.txt
        pip install markdown
        pip install osbot-utils

    - name: Run tests with pytest (with coverage)
      shell: bash
      run: |
        coverage run --source=osbot_markdown -m pytest -v -s --durations=0 tests